version: '3.4'

services:
  api:
    image: fahad438/munasibty-backend:latest
    build: .
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
